#!/bin/bash

# Pick a dict file randomly (if many)
DictDir=/usr/share/dict
SymbolsFile=./symbols
DictCount=$(ls -A ${DictDir} | wc -l)
DictFile=${DictDir}/$(ls -A $DictDir | sed -n "$(( $RANDOM % $DictCount + 1 ))p")
DictLen=$( wc -l < ${DictFile})

# Show correct usage
function usage() {
	cat <<- _EOF_
		PASSWORD-MAKER
		Usage:
		${0} NO_OF_WORDS MAX_NUM_LEN
	_EOF_
}


# Random Word
function randomWord() {
	local i=$1
	local Len=$2
	local Dictionary=$3
	if (( i == 0 && MaxNumLen !=0 ))
	then
		printf "%d" $(( ( $RANDOM * $RANDOM ) % ( 10 ** $MaxNumLen) ))
	else
		sed -n "$(( $RANDOM % $Len + 1 ))p" $Dictionary | sed -e "s/^\(.\)/\u\1/g"
	fi
	return
}

# Random Symbol
function randomSymbol() {
	local Len=$(wc -l < ${SymbolsFile})
	if (( $RANDOM % 2 ))
	then
		sed -n "$(( $RANDOM % $Len + 1 ))p" $SymbolsFile
	fi
	return
}

# Input Validation
if [[ "$#" -eq 0 ]]
then
	PhraseCount=3
	MaxNumLen=4
elif [[ "$#" -eq 1 ]]
then
	PhraseCount=$1
	MaxNumLen=0
elif [[ "$#" -lt 2 || ! "$1" =~ ^[0-9]+$ || ! "$2" =~ ^[0-9]+$ ]] 
then
	echo "${0}: Bad Usage" >&2
	usage
	exit 1
else
	PhraseCount=$1
	MaxNumLen=$2
fi

# - - - - - - - - - - - - - - - - - - - -
# Main Program
for (( j=0; j<10; j++))
do
	for (( i=0;i<=PhraseCount;i++ ))
	do
		printf "%s" $(randomWord $i $DictLen $DictFile)
		if (( i < PhraseCount - 1 ))
		then
			printf "%s" $(randomSymbol)
		fi
	done
	echo ""
done
# - - - - - - - - - - - - - - - - - - - -
